import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import { Inter, JetBrains_Mono } from 'next/font/google';
import './index.css';

const inter = Inter({
    variable: '--font-sans',
    subsets: ['latin']
});

const jetBrainsMono = JetBrains_Mono({
    variable: '--font-mono',
    subsets: ['latin']
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default ({
    children
}: Readonly<{
    children: React.ReactNode;
}>) => {
    return (
        <html className="h-full bg-background focus-within:scroll-smooth" lang="en" suppressHydrationWarning>
            <body className={`${inter.variable} ${jetBrainsMono.variable} h-full antialiased`}>
                <ThemeProvider enableSystem disableTransitionOnChange defaultTheme="system" attribute="class">
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
};
